# Generated by Django 4.2.6 on 2023-10-14 17:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("galeria", "0004_fotografia_data_fotogtafia"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fotografia",
            old_name="data_fotogtafia",
            new_name="data_fotografia",
        ),
    ]
